export const detailedBusinessCardsMock = [
    {
        id: 1,
        image: "/images/business_abstract.jpg",
        price: "1 780 000 000 сум",
        title: "Готовый бизнес по доставке еды",
        address: "г. Ташкент, ул. Якуба Коласа, 2",
        area: "150 кв. м.",
        popular: true,
    },
    {
        id: 2,
        image: "/images/business_abstract.jpg",
        price: "940 000 000 сум",
        title: "Мини-пекарня у метро",
        address: "г. Самарканд, ул. Амир Темур, 17",
        area: "60 кв. м.",
        popular: false,
    },
    {
        id: 3,
        image: "/images/business_abstract.jpg",
        price: "2 250 000 000 сум",
        title: "Магазин одежды премиум класса",
        address: "г. Бухара, ул. Нафиса, 4А",
        area: "120 кв. м.",
        popular: true,
    },
    {
        id: 4,
        image: "/images/business_abstract.jpg",
        price: "1 300 000 000 сум",
        title: "Детский развивающий центр",
        address: "г. Фергана, ул. Навои, 11",
        area: "90 кв. м.",
        popular: true,
    },
    {
        id: 5,
        image: "/images/business_abstract.jpg",
        price: "580 000 000 сум",
        title: "Кофейня в центре города",
        address: "г. Ташкент, ул. Шота Руставели, 10",
        area: "45 кв. м.",
        popular: false,
    },
    {
        id: 6,
        image: "/images/business_abstract.jpg",
        price: "3 100 000 000 сум",
        title: "Сеть автомоек",
        address: "г. Андижан, ул. Гулистон, 22",
        area: "300 кв. м.",
        popular: true,
    },
    {
        id: 7,
        image: "/images/business_abstract.jpg",
        price: "870 000 000 сум",
        title: "Салон красоты с оборудованием",
        address: "г. Нукус, ул. Хамза, 9",
        area: "75 кв. м.",
        popular: true,
    },
    {
        id: 8,
        image: "/images/business_abstract.jpg",
        price: "1 000 000 000 сум",
        title: "Магазин бытовой техники",
        address: "г. Джизак, ул. Мустакиллик, 14",
        area: "110 кв. м.",
        popular: false,
    },
    {
        id: 9,
        image: "/images/business_abstract.jpg",
        price: "620 000 000 сум",
        title: "Цветочный бутик",
        address: "г. Термез, ул. Фарход, 6",
        area: "35 кв. м.",
        popular: false,
    },
    {
        id: 10,
        image: "/images/business_abstract.jpg",
        price: "2 900 000 000 сум",
        title: "Производство мебели",
        address: "г. Наманган, ул. Алишера Навои, 20",
        area: "250 кв. м.",
        popular: true,
    },
    {
        id: 11,
        image: "/images/business_abstract.jpg",
        price: "710 000 000 сум",
        title: "Швейный цех",
        address: "г. Карши, ул. Буюк Ипак Йули, 5",
        area: "100 кв. м.",
        popular: false,
    },
    {
        id: 12,
        image: "/images/business_abstract.jpg",
        price: "1 500 000 000 сум",
        title: "Фастфуд в торговом центре",
        address: "г. Ташкент, ТРЦ Mega Planet",
        area: "80 кв. м.",
        popular: true,
    },
    {
        id: 13,
        image: "/images/business_abstract.jpg",
        price: "2 150 000 000 сум",
        title: "Фитнес клуб с клиентской базой",
        address: "г. Ургенч, ул. Спорт, 7",
        area: "180 кв. м.",
        popular: true,
    },
];
