export const TempBusinessCardsMock = [
  {
    "id": 1,
    "image": "/images/business_abstract.jpg",
    "price": "1 780 000 000 сум",
    "title": "Готовый бизнес по доставке еды",
    "address": "ул. Якуба Коласа, 2",
    "city": "Ташкент",
    "area": "150 кв. м.",
    "popular": true,
    "type": "франшиза"
  },
  {
    "id": 2,
    "image": "/images/business_abstract.jpg",
    "price": "940 000 000 сум",
    "title": "Мини-пекарня у метро",
    "address": "ул. Амир Темур, 17",
    "city": "Самарканд",
    "area": "60 кв. м.",
    "popular": false,
    "type": "франшиза"
  },
  {
    "id": 3,
    "image": "/images/business_abstract.jpg",
    "price": "2 250 000 000 сум",
    "title": "Магазин одежды премиум класса",
    "address": "ул. Нафиса, 4А",
    "city": "Бухара",
    "area": "120 кв. м.",
    "popular": true,
    "type": "стартап"
  },
  {
    "id": 4,
    "image": "/images/business_abstract.jpg",
    "price": "1 300 000 000 сум",
    "title": "Детский развивающий центр",
    "address": "ул. Навои, 11",
    "city": "Фергана",
    "area": "90 кв. м.",
    "popular": true,
    "type": "бизнес"
  },
  {
    "id": 5,
    "image": "/images/business_abstract.jpg",
    "price": "580 000 000 сум",
    "title": "Кофейня в центре города",
    "address": "ул. Шота Руставели, 10",
    "city": "Ташкент",
    "area": "45 кв. м.",
    "popular": false,
    "type": "бизнес"
  },
  {
    "id": 6,
    "image": "/images/business_abstract.jpg",
    "price": "3 100 000 000 сум",
    "title": "Сеть автомоек",
    "address": "ул. Гулистон, 22",
    "city": "Андижан",
    "area": "300 кв. м.",
    "popular": true,
    "type": "стартап"
  },
  {
    "id": 7,
    "image": "/images/business_abstract.jpg",
    "price": "870 000 000 сум",
    "title": "Салон красоты с оборудованием",
    "address": "ул. Хамза, 9",
    "city": "Нукус",
    "area": "75 кв. м.",
    "popular": true,
    "type": "бизнес"
  },
  {
    "id": 8,
    "image": "/images/business_abstract.jpg",
    "price": "1 000 000 000 сум",
    "title": "Магазин бытовой техники",
    "address": "ул. Мустакиллик, 14",
    "city": "Джизак",
    "area": "110 кв. м.",
    "popular": false,
    "type": "инвестиции"
  },
  {
    "id": 9,
    "image": "/images/business_abstract.jpg",
    "price": "620 000 000 сум",
    "title": "Цветочный бутик",
    "address": "ул. Фарход, 6",
    "city": "Термез",
    "area": "35 кв. м.",
    "popular": false,
    "type": "франшиза"
  },
  {
    "id": 10,
    "image": "/images/business_abstract.jpg",
    "price": "2 900 000 000 сум",
    "title": "Производство мебели",
    "address": "Алишера Навои, 20",
    "city": "Наманган",
    "area": "250 кв. м.",
    "popular": true,
    "type": "франшиза"
  },
  {
    "id": 11,
    "image": "/images/business_abstract.jpg",
    "price": "710 000 000 сум",
    "title": "Швейный цех",
    "address": "ул. Буюк Ипак Йули, 5",
    "city": "Карши",
    "area": "100 кв. м.",
    "popular": false,
    "type": "стартап"
  },
  {
    "id": 12,
    "image": "/images/business_abstract.jpg",
    "price": "1 500 000 000 сум",
    "title": "Фастфуд в торговом центре",
    "address": "ТРЦ Mega Planet",
    "city": "Ташкент",
    "area": "80 кв. м.",
    "popular": true,
    "type": "инвестиции"
  },
  {
    "id": 13,
    "image": "/images/business_abstract.jpg",
    "price": "2 150 000 000 сум",
    "title": "Фитнес клуб с клиентской базой",
    "address": "ул. Спорт, 7",
    "city": "Ургенч",
    "area": "180 кв. м.",
    "popular": true,
    "type": "инвестиции"
  },
  {
    "id": 14,
    "image": "/images/business_abstract.jpg",
    "price": "1633 000 000 сум",
    "title": "IT-стартап",
    "address": "ул. Мустакиллик, 24",
    "city": "Андижан",
    "area": "77 кв. м.",
    "popular": true,
    "type": "инвестиции"
  },
  {
    "id": 15,
    "image": "/images/business_abstract.jpg",
    "price": "2769 000 000 сум",
    "title": "Парикмахерская",
    "address": "ул. Навои, 14",
    "city": "Самарканд",
    "area": "116 кв. м.",
    "popular": false,
    "type": "бизнес"
  },
  {
    "id": 16,
    "image": "/images/business_abstract.jpg",
    "price": "1417 000 000 сум",
    "title": "Ресторан",
    "address": "ул. Навои, 26",
    "city": "Термез",
    "area": "120 кв. м.",
    "popular": true,
    "type": "инвестиции"
  },
  {
    "id": 17,
    "image": "/images/business_abstract.jpg",
    "price": "700 000 000 сум",
    "title": "Фитнес-зал",
    "address": "ул. Навои, 18",
    "city": "Нукус",
    "area": "339 кв. м.",
    "popular": false,
    "type": "бизнес"
  },
  {
    "id": 18,
    "image": "/images/business_abstract.jpg",
    "price": "2926 000 000 сум",
    "title": "IT-стартап",
    "address": "ул. Навои, 25",
    "city": "Джизак",
    "area": "175 кв. м.",
    "popular": true,
    "type": "инвестиции"
  },
  {
    "id": 19,
    "image": "/images/business_abstract.jpg",
    "price": "2760 000 000 сум",
    "title": "Парикмахерская",
    "address": "ул. Мустакиллик, 19",
    "city": "Фергана",
    "area": "175 кв. м.",
    "popular": true,
    "type": "франшиза"
  },
  {
    "id": 20,
    "image": "/images/business_abstract.jpg",
    "price": "2709 000 000 сум",
    "title": "Франшиза кафе",
    "address": "ул. Фарход, 23",
    "city": "Наманган",
    "area": "198 кв. м.",
    "popular": false,
    "type": "франшиза"
  },
  {
    "id": 21,
    "image": "/images/business_abstract.jpg",
    "price": "979 000 000 сум",
    "title": "Аптека",
    "address": "ул. Мустакиллик, 8",
    "city": "Термез",
    "area": "284 кв. м.",
    "popular": false,
    "type": "инвестиции"
  },
  {
    "id": 22,
    "image": "/images/business_abstract.jpg",
    "price": "838 000 000 сум",
    "title": "Фудтрак",
    "address": "ул. Навои, 21",
    "city": "Фергана",
    "area": "233 кв. м.",
    "popular": true,
    "type": "стартап"
  },
  {
    "id": 23,
    "image": "/images/business_abstract.jpg",
    "price": "2954 000 000 сум",
    "title": "Коворкинг",
    "address": "ул. Навои, 10",
    "city": "Андижан",
    "area": "311 кв. м.",
    "popular": false,
    "type": "стартап"
  },
  {
    "id": 24,
    "image": "/images/business_abstract.jpg",
    "price": "1631 000 000 сум",
    "title": "Ресторан",
    "address": "ул. Навои, 1",
    "city": "Ургенч",
    "area": "194 кв. м.",
    "popular": true,
    "type": "стартап"
  },
  {
    "id": 25,
    "image": "/images/business_abstract.jpg",
    "price": "1966 000 000 сум",
    "title": "Фитнес-зал",
    "address": "ул. Мустакиллик, 20",
    "city": "Термез",
    "area": "142 кв. м.",
    "popular": true,
    "type": "франшиза"
  },
  {
    "id": 26,
    "image": "/images/business_abstract.jpg",
    "price": "2083 000 000 сум",
    "title": "Производство",
    "address": "ул. Навои, 4",
    "city": "Самарканд",
    "area": "111 кв. м.",
    "popular": false,
    "type": "франшиза"
  },
  {
    "id": 27,
    "image": "/images/business_abstract.jpg",
    "price": "803 000 000 сум",
    "title": "Ресторан",
    "address": "ул. Навои, 13",
    "city": "Андижан",
    "area": "277 кв. м.",
    "popular": true,
    "type": "бизнес"
  },
  {
    "id": 28,
    "image": "/images/business_abstract.jpg",
    "price": "2675 000 000 сум",
    "title": "Производство",
    "address": "ул. Фарход, 29",
    "city": "Ташкент",
    "area": "74 кв. м.",
    "popular": true,
    "type": "франшиза"
  },
  {
    "id": 29,
    "image": "/images/business_abstract.jpg",
    "price": "2402 000 000 сум",
    "title": "IT-стартап",
    "address": "ул. Темур, 10",
    "city": "Карши",
    "area": "197 кв. м.",
    "popular": false,
    "type": "стартап"
  },
  {
    "id": 30,
    "image": "/images/business_abstract.jpg",
    "price": "1938 000 000 сум",
    "title": "Аптека",
    "address": "ул. Мустакиллик, 26",
    "city": "Самарканд",
    "area": "50 кв. м.",
    "popular": false,
    "type": "стартап"
  },
  {
    "id": 31,
    "image": "/images/business_abstract.jpg",
    "price": "1615 000 000 сум",
    "title": "Фитнес-зал",
    "address": "ул. Мустакиллик, 30",
    "city": "Бухара",
    "area": "173 кв. м.",
    "popular": true,
    "type": "франшиза"
  },
  {
    "id": 32,
    "image": "/images/business_abstract.jpg",
    "price": "635 000 000 сум",
    "title": "IT-стартап",
    "address": "ул. Навои, 1",
    "city": "Бухара",
    "area": "258 кв. м.",
    "popular": true,
    "type": "франшиза"
  },
  {
    "id": 33,
    "image": "/images/business_abstract.jpg",
    "price": "915 000 000 сум",
    "title": "Ресторан",
    "address": "ул. Навои, 21",
    "city": "Бухара",
    "area": "147 кв. м.",
    "popular": true,
    "type": "бизнес"
  },
  {
    "id": 34,
    "image": "/images/business_abstract.jpg",
    "price": "1680 000 000 сум",
    "title": "Коворкинг",
    "address": "ул. Мустакиллик, 6",
    "city": "Джизак",
    "area": "125 кв. м.",
    "popular": false,
    "type": "бизнес"
  },
  {
    "id": 35,
    "image": "/images/business_abstract.jpg",
    "price": "1518 000 000 сум",
    "title": "Коворкинг",
    "address": "ул. Мустакиллик, 22",
    "city": "Фергана",
    "area": "266 кв. м.",
    "popular": true,
    "type": "франшиза"
  },
  {
    "id": 36,
    "image": "/images/business_abstract.jpg",
    "price": "1795 000 000 сум",
    "title": "Франшиза кафе",
    "address": "ул. Темур, 15",
    "city": "Термез",
    "area": "86 кв. м.",
    "popular": true,
    "type": "стартап"
  },
  {
    "id": 37,
    "image": "/images/business_abstract.jpg",
    "price": "1717 000 000 сум",
    "title": "IT-стартап",
    "address": "ул. Фарход, 4",
    "city": "Ургенч",
    "area": "216 кв. м.",
    "popular": false,
    "type": "инвестиции"
  },
  {
    "id": 38,
    "image": "/images/business_abstract.jpg",
    "price": "975 000 000 сум",
    "title": "Парикмахерская",
    "address": "ул. Темур, 2",
    "city": "Нукус",
    "area": "349 кв. м.",
    "popular": true,
    "type": "инвестиции"
  },
  {
    "id": 39,
    "image": "/images/business_abstract.jpg",
    "price": "2288 000 000 сум",
    "title": "Фудтрак",
    "address": "ул. Мустакиллик, 19",
    "city": "Ургенч",
    "area": "37 кв. м.",
    "popular": true,
    "type": "бизнес"
  },
  {
    "id": 40,
    "image": "/images/business_abstract.jpg",
    "price": "1388 000 000 сум",
    "title": "Пекарня",
    "address": "ул. Темур, 10",
    "city": "Бухара",
    "area": "108 кв. м.",
    "popular": true,
    "type": "стартап"
  },
  {
    "id": 41,
    "image": "/images/business_abstract.jpg",
    "price": "2342 000 000 сум",
    "title": "Фудтрак",
    "address": "ул. Навои, 26",
    "city": "Карши",
    "area": "34 кв. м.",
    "popular": true,
    "type": "стартап"
  },
  {
    "id": 42,
    "image": "/images/business_abstract.jpg",
    "price": "2921 000 000 сум",
    "title": "Аптека",
    "address": "ул. Темур, 14",
    "city": "Ургенч",
    "area": "240 кв. м.",
    "popular": true,
    "type": "инвестиции"
  },
  {
    "id": 43,
    "image": "/images/business_abstract.jpg",
    "price": "2545 000 000 сум",
    "title": "IT-стартап",
    "address": "ул. Мустакиллик, 7",
    "city": "Джизак",
    "area": "334 кв. м.",
    "popular": true,
    "type": "франшиза"
  },
  {
    "id": 44,
    "image": "/images/business_abstract.jpg",
    "price": "1852 000 000 сум",
    "title": "Ресторан",
    "address": "ул. Фарход, 25",
    "city": "Джизак",
    "area": "85 кв. м.",
    "popular": true,
    "type": "стартап"
  },
  {
    "id": 45,
    "image": "/images/business_abstract.jpg",
    "price": "2624 000 000 сум",
    "title": "IT-стартап",
    "address": "ул. Темур, 8",
    "city": "Нукус",
    "area": "86 кв. м.",
    "popular": true,
    "type": "бизнес"
  },
  {
    "id": 46,
    "image": "/images/business_abstract.jpg",
    "price": "590 000 000 сум",
    "title": "Производство",
    "address": "ул. Мустакиллик, 23",
    "city": "Джизак",
    "area": "187 кв. м.",
    "popular": true,
    "type": "стартап"
  },
  {
    "id": 47,
    "image": "/images/business_abstract.jpg",
    "price": "1782 000 000 сум",
    "title": "Фитнес-зал",
    "address": "ул. Фарход, 5",
    "city": "Джизак",
    "area": "320 кв. м.",
    "popular": false,
    "type": "бизнес"
  },
  {
    "id": 48,
    "image": "/images/business_abstract.jpg",
    "price": "881 000 000 сум",
    "title": "Ресторан",
    "address": "ул. Темур, 27",
    "city": "Андижан",
    "area": "277 кв. м.",
    "popular": false,
    "type": "франшиза"
  },
  {
    "id": 49,
    "image": "/images/business_abstract.jpg",
    "price": "1340 000 000 сум",
    "title": "Парикмахерская",
    "address": "ул. Темур, 24",
    "city": "Джизак",
    "area": "179 кв. м.",
    "popular": false,
    "type": "франшиза"
  },
  {
    "id": 50,
    "image": "/images/business_abstract.jpg",
    "price": "1592 000 000 сум",
    "title": "Парикмахерская",
    "address": "ул. Темур, 24",
    "city": "Джизак",
    "area": "182 кв. м.",
    "popular": true,
    "type": "франшиза"
  },
  {
    "id": 51,
    "image": "/images/business_abstract.jpg",
    "price": "2645 000 000 сум",
    "title": "Пекарня",
    "address": "ул. Темур, 2",
    "city": "Наманган",
    "area": "337 кв. м.",
    "popular": false,
    "type": "бизнес"
  },
  {
    "id": 52,
    "image": "/images/business_abstract.jpg",
    "price": "2238 000 000 сум",
    "title": "Производство",
    "address": "ул. Мустакиллик, 23",
    "city": "Джизак",
    "area": "287 кв. м.",
    "popular": true,
    "type": "стартап"
  },
  {
    "id": 53,
    "image": "/images/business_abstract.jpg",
    "price": "1686 000 000 сум",
    "title": "Фудтрак",
    "address": "ул. Навои, 9",
    "city": "Фергана",
    "area": "314 кв. м.",
    "popular": true,
    "type": "стартап"
  },
  {
    "id": 54,
    "image": "/images/business_abstract.jpg",
    "price": "2473 000 000 сум",
    "title": "Аптека",
    "address": "ул. Темур, 30",
    "city": "Нукус",
    "area": "108 кв. м.",
    "popular": false,
    "type": "бизнес"
  },
  {
    "id": 55,
    "image": "/images/business_abstract.jpg",
    "price": "1954 000 000 сум",
    "title": "Коворкинг",
    "address": "ул. Фарход, 1",
    "city": "Нукус",
    "area": "91 кв. м.",
    "popular": false,
    "type": "стартап"
  },
  {
    "id": 56,
    "image": "/images/business_abstract.jpg",
    "price": "1419 000 000 сум",
    "title": "Пекарня",
    "address": "ул. Темур, 21",
    "city": "Ургенч",
    "area": "250 кв. м.",
    "popular": true,
    "type": "стартап"
  },
  {
    "id": 57,
    "image": "/images/business_abstract.jpg",
    "price": "2022 000 000 сум",
    "title": "Фитнес-зал",
    "address": "ул. Мустакиллик, 4",
    "city": "Андижан",
    "area": "82 кв. м.",
    "popular": false,
    "type": "франшиза"
  },
  {
    "id": 58,
    "image": "/images/business_abstract.jpg",
    "price": "1732 000 000 сум",
    "title": "Коворкинг",
    "address": "ул. Темур, 8",
    "city": "Нукус",
    "area": "105 кв. м.",
    "popular": true,
    "type": "франшиза"
  },
  {
    "id": 59,
    "image": "/images/business_abstract.jpg",
    "price": "1168 000 000 сум",
    "title": "Парикмахерская",
    "address": "ул. Темур, 19",
    "city": "Бухара",
    "area": "131 кв. м.",
    "popular": false,
    "type": "инвестиции"
  },
  {
    "id": 60,
    "image": "/images/business_abstract.jpg",
    "price": "2910 000 000 сум",
    "title": "Аптека",
    "address": "ул. Навои, 20",
    "city": "Ташкент",
    "area": "255 кв. м.",
    "popular": false,
    "type": "инвестиции"
  },
  {
    "id": 61,
    "image": "/images/business_abstract.jpg",
    "price": "1440 000 000 сум",
    "title": "Фитнес-зал",
    "address": "ул. Темур, 13",
    "city": "Термез",
    "area": "269 кв. м.",
    "popular": true,
    "type": "франшиза"
  },
  {
    "id": 62,
    "image": "/images/business_abstract.jpg",
    "price": "1634 000 000 сум",
    "title": "Франшиза кафе",
    "address": "ул. Фарход, 27",
    "city": "Ташкент",
    "area": "266 кв. м.",
    "popular": true,
    "type": "инвестиции"
  },
  {
    "id": 63,
    "image": "/images/business_abstract.jpg",
    "price": "592 000 000 сум",
    "title": "Парикмахерская",
    "address": "ул. Темур, 3",
    "city": "Нукус",
    "area": "216 кв. м.",
    "popular": true,
    "type": "инвестиции"
  },
  {
    "id": 64,
    "image": "/images/business_abstract.jpg",
    "price": "2857 000 000 сум",
    "title": "Фитнес-зал",
    "address": "ул. Навои, 22",
    "city": "Карши",
    "area": "58 кв. м.",
    "popular": false,
    "type": "инвестиции"
  },
  {
    "id": 65,
    "image": "/images/business_abstract.jpg",
    "price": "1080 000 000 сум",
    "title": "Производство",
    "address": "ул. Мустакиллик, 22",
    "city": "Самарканд",
    "area": "56 кв. м.",
    "popular": true,
    "type": "стартап"
  },
  {
    "id": 66,
    "image": "/images/business_abstract.jpg",
    "price": "992 000 000 сум",
    "title": "IT-стартап",
    "address": "ул. Темур, 13",
    "city": "Термез",
    "area": "34 кв. м.",
    "popular": true,
    "type": "франшиза"
  },
  {
    "id": 67,
    "image": "/images/business_abstract.jpg",
    "price": "1896 000 000 сум",
    "title": "Пекарня",
    "address": "ул. Навои, 6",
    "city": "Бухара",
    "area": "87 кв. м.",
    "popular": true,
    "type": "франшиза"
  },
  {
    "id": 68,
    "image": "/images/business_abstract.jpg",
    "price": "2190 000 000 сум",
    "title": "Фудтрак",
    "address": "ул. Фарход, 19",
    "city": "Наманган",
    "area": "220 кв. м.",
    "popular": true,
    "type": "франшиза"
  },
  {
    "id": 69,
    "image": "/images/business_abstract.jpg",
    "price": "588 000 000 сум",
    "title": "Франшиза кафе",
    "address": "ул. Навои, 1",
    "city": "Ургенч",
    "area": "151 кв. м.",
    "popular": true,
    "type": "бизнес"
  },
  {
    "id": 70,
    "image": "/images/business_abstract.jpg",
    "price": "2387 000 000 сум",
    "title": "Ресторан",
    "address": "ул. Фарход, 2",
    "city": "Джизак",
    "area": "91 кв. м.",
    "popular": false,
    "type": "инвестиции"
  },
  {
    "id": 71,
    "image": "/images/business_abstract.jpg",
    "price": "1406 000 000 сум",
    "title": "Парикмахерская",
    "address": "ул. Темур, 14",
    "city": "Карши",
    "area": "343 кв. м.",
    "popular": false,
    "type": "стартап"
  },
  {
    "id": 72,
    "image": "/images/business_abstract.jpg",
    "price": "2563 000 000 сум",
    "title": "Франшиза кафе",
    "address": "ул. Темур, 7",
    "city": "Бухара",
    "area": "267 кв. м.",
    "popular": true,
    "type": "стартап"
  },
  {
    "id": 73,
    "image": "/images/business_abstract.jpg",
    "price": "849 000 000 сум",
    "title": "Франшиза кафе",
    "address": "ул. Фарход, 12",
    "city": "Карши",
    "area": "285 кв. м.",
    "popular": true,
    "type": "бизнес"
  },
  {
    "id": 74,
    "image": "/images/business_abstract.jpg",
    "price": "1867 000 000 сум",
    "title": "Фитнес-зал",
    "address": "ул. Мустакиллик, 2",
    "city": "Нукус",
    "area": "32 кв. м.",
    "popular": false,
    "type": "инвестиции"
  },
  {
    "id": 75,
    "image": "/images/business_abstract.jpg",
    "price": "1489 000 000 сум",
    "title": "Производство",
    "address": "ул. Темур, 30",
    "city": "Нукус",
    "area": "138 кв. м.",
    "popular": false,
    "type": "франшиза"
  },
  {
    "id": 76,
    "image": "/images/business_abstract.jpg",
    "price": "2892 000 000 сум",
    "title": "Коворкинг",
    "address": "ул. Темур, 8",
    "city": "Наманган",
    "area": "295 кв. м.",
    "popular": false,
    "type": "инвестиции"
  },
  {
    "id": 77,
    "image": "/images/business_abstract.jpg",
    "price": "2911 000 000 сум",
    "title": "IT-стартап",
    "address": "ул. Мустакиллик, 9",
    "city": "Джизак",
    "area": "210 кв. м.",
    "popular": true,
    "type": "бизнес"
  },
  {
    "id": 78,
    "image": "/images/business_abstract.jpg",
    "price": "2209 000 000 сум",
    "title": "Ресторан",
    "address": "ул. Навои, 21",
    "city": "Нукус",
    "area": "243 кв. м.",
    "popular": true,
    "type": "инвестиции"
  },
  {
    "id": 79,
    "image": "/images/business_abstract.jpg",
    "price": "844 000 000 сум",
    "title": "Производство",
    "address": "ул. Навои, 1",
    "city": "Нукус",
    "area": "148 кв. м.",
    "popular": true,
    "type": "бизнес"
  },
  {
    "id": 80,
    "image": "/images/business_abstract.jpg",
    "price": "1946 000 000 сум",
    "title": "Парикмахерская",
    "address": "ул. Навои, 24",
    "city": "Ургенч",
    "area": "202 кв. м.",
    "popular": false,
    "type": "бизнес"
  },
  {
    "id": 81,
    "image": "/images/business_abstract.jpg",
    "price": "2380 000 000 сум",
    "title": "Аптека",
    "address": "ул. Навои, 21",
    "city": "Бухара",
    "area": "99 кв. м.",
    "popular": true,
    "type": "франшиза"
  },
  {
    "id": 82,
    "image": "/images/business_abstract.jpg",
    "price": "2780 000 000 сум",
    "title": "Пекарня",
    "address": "ул. Темур, 8",
    "city": "Ургенч",
    "area": "194 кв. м.",
    "popular": true,
    "type": "стартап"
  },
  {
    "id": 83,
    "image": "/images/business_abstract.jpg",
    "price": "2165 000 000 сум",
    "title": "Коворкинг",
    "address": "ул. Фарход, 30",
    "city": "Джизак",
    "area": "236 кв. м.",
    "popular": false,
    "type": "инвестиции"
  },
  {
    "id": 84,
    "image": "/images/business_abstract.jpg",
    "price": "1021 000 000 сум",
    "title": "Фитнес-зал",
    "address": "ул. Темур, 29",
    "city": "Бухара",
    "area": "222 кв. м.",
    "popular": true,
    "type": "инвестиции"
  },
  {
    "id": 85,
    "image": "/images/business_abstract.jpg",
    "price": "823 000 000 сум",
    "title": "Фитнес-зал",
    "address": "ул. Навои, 25",
    "city": "Ташкент",
    "area": "252 кв. м.",
    "popular": true,
    "type": "стартап"
  },
  {
    "id": 86,
    "image": "/images/business_abstract.jpg",
    "price": "1768 000 000 сум",
    "title": "Франшиза кафе",
    "address": "ул. Мустакиллик, 17",
    "city": "Андижан",
    "area": "328 кв. м.",
    "popular": true,
    "type": "бизнес"
  },
  {
    "id": 87,
    "image": "/images/business_abstract.jpg",
    "price": "524 000 000 сум",
    "title": "Парикмахерская",
    "address": "ул. Навои, 11",
    "city": "Наманган",
    "area": "275 кв. м.",
    "popular": false,
    "type": "бизнес"
  },
  {
    "id": 88,
    "image": "/images/business_abstract.jpg",
    "price": "2023 000 000 сум",
    "title": "Франшиза кафе",
    "address": "ул. Фарход, 17",
    "city": "Бухара",
    "area": "101 кв. м.",
    "popular": true,
    "type": "бизнес"
  },
  {
    "id": 89,
    "image": "/images/business_abstract.jpg",
    "price": "552 000 000 сум",
    "title": "Аптека",
    "address": "ул. Навои, 2",
    "city": "Бухара",
    "area": "335 кв. м.",
    "popular": false,
    "type": "стартап"
  },
  {
    "id": 90,
    "image": "/images/business_abstract.jpg",
    "price": "1507 000 000 сум",
    "title": "Парикмахерская",
    "address": "ул. Мустакиллик, 1",
    "city": "Ургенч",
    "area": "150 кв. м.",
    "popular": false,
    "type": "инвестиции"
  },
  {
    "id": 91,
    "image": "/images/business_abstract.jpg",
    "price": "2860 000 000 сум",
    "title": "Франшиза кафе",
    "address": "ул. Навои, 27",
    "city": "Ташкент",
    "area": "70 кв. м.",
    "popular": false,
    "type": "франшиза"
  },
  {
    "id": 92,
    "image": "/images/business_abstract.jpg",
    "price": "2135 000 000 сум",
    "title": "Парикмахерская",
    "address": "ул. Темур, 6",
    "city": "Ургенч",
    "area": "310 кв. м.",
    "popular": false,
    "type": "стартап"
  },
  {
    "id": 93,
    "image": "/images/business_abstract.jpg",
    "price": "696 000 000 сум",
    "title": "Франшиза кафе",
    "address": "ул. Фарход, 26",
    "city": "Бухара",
    "area": "248 кв. м.",
    "popular": false,
    "type": "франшиза"
  },
  {
    "id": 94,
    "image": "/images/business_abstract.jpg",
    "price": "2744 000 000 сум",
    "title": "Фудтрак",
    "address": "ул. Фарход, 13",
    "city": "Ташкент",
    "area": "335 кв. м.",
    "popular": false,
    "type": "инвестиции"
  },
  {
    "id": 95,
    "image": "/images/business_abstract.jpg",
    "price": "723 000 000 сум",
    "title": "Фитнес-зал",
    "address": "ул. Фарход, 19",
    "city": "Самарканд",
    "area": "322 кв. м.",
    "popular": true,
    "type": "франшиза"
  },
  {
    "id": 96,
    "image": "/images/business_abstract.jpg",
    "price": "2088 000 000 сум",
    "title": "Фудтрак",
    "address": "ул. Навои, 17",
    "city": "Ургенч",
    "area": "161 кв. м.",
    "popular": true,
    "type": "бизнес"
  },
  {
    "id": 97,
    "image": "/images/business_abstract.jpg",
    "price": "883 000 000 сум",
    "title": "Ресторан",
    "address": "ул. Фарход, 3",
    "city": "Джизак",
    "area": "44 кв. м.",
    "popular": true,
    "type": "стартап"
  },
  {
    "id": 98,
    "image": "/images/business_abstract.jpg",
    "price": "2965 000 000 сум",
    "title": "Ресторан",
    "address": "ул. Мустакиллик, 20",
    "city": "Ташкент",
    "area": "111 кв. м.",
    "popular": true,
    "type": "инвестиции"
  },
  {
    "id": 99,
    "image": "/images/business_abstract.jpg",
    "price": "1964 000 000 сум",
    "title": "Производство",
    "address": "ул. Мустакиллик, 23",
    "city": "Джизак",
    "area": "81 кв. м.",
    "popular": false,
    "type": "стартап"
  },
  {
    "id": 100,
    "image": "/images/business_abstract.jpg",
    "price": "1944 000 000 сум",
    "title": "Аптека",
    "address": "ул. Темур, 20",
    "city": "Джизак",
    "area": "248 кв. м.",
    "popular": true,
    "type": "бизнес"
  }
];